--
-- Script was generated by Devart dbForge Studio 2019 for MySQL, Version 8.1.22.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 2023. 04. 03. 19:06:30
-- Server version: 5.5.5-10.4.25-MariaDB
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

--
-- Set default database
--
USE verseny;

--
-- Drop table `competition board`
--
DROP TABLE IF EXISTS `competition board`;

--
-- Drop table `competitions`
--
DROP TABLE IF EXISTS competitions;

--
-- Drop table `students`
--
DROP TABLE IF EXISTS students;

--
-- Set default database
--
USE verseny;

--
-- Create table `students`
--
CREATE TABLE IF NOT EXISTS students (
  Id INT(11) NOT NULL AUTO_INCREMENT,
  Name VARCHAR(50) DEFAULT NULL,
  TestScore VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (Id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 4,
AVG_ROW_LENGTH = 5461,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create table `competitions`
--
CREATE TABLE IF NOT EXISTS competitions (
  Id INT(11) NOT NULL AUTO_INCREMENT,
  competitionName VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (Id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 4,
AVG_ROW_LENGTH = 5461,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create table `competition board`
--
CREATE TABLE IF NOT EXISTS `competition board` (
  studentId INT(11) DEFAULT NULL,
  Ranking VARCHAR(255) DEFAULT NULL,
  competitionId INT(11) DEFAULT NULL
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 5461,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create foreign key
--
ALTER TABLE `competition board` 
  ADD CONSTRAINT `FK_competition board_competitions_Id` FOREIGN KEY (competitionId)
    REFERENCES competitions(Id);

--
-- Create foreign key
--
ALTER TABLE `competition board` 
  ADD CONSTRAINT `FK_competition board_students_Id` FOREIGN KEY (studentId)
    REFERENCES students(Id);

-- 
-- Dumping data for table students
--
INSERT INTO students VALUES
(1, 'Corey Hass', '79'),
(2, 'Leroy Kunze', '93'),
(3, 'Ezekiel Bullard', '65');

-- 
-- Dumping data for table competitions
--
INSERT INTO competitions VALUES
(1, 'Harvard/MIT Mathematics Tournament (HMMT)'),
(2, 'ELA and the Arts Student Contests'),
(3, 'Space Settlement Design Competitions');

-- 
-- Dumping data for table `competition board`
--
INSERT INTO `competition board` VALUES
(1, '23.', 3),
(2, '8.', 1),
(3, '74.', 2);

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;